### ISSUE TITLE
support fastjson in this plugin

### ISSUE THREAD

**Issue by ccqy66** [robohorse/RoboPOJOGenerator#53]
Most of the time,the people around me uses fastjson to deserialize json,and the fastjson is widely used,so, It's so excited if the  plugin support fastjson.Of course, I am also glad to do it if you'd like.

**Comment by robohorse** [comment]
hmm... Do you mean [this](https://github.com/alibaba/fastjson)? I cant found information about it's annotations. Without annotations support of this parser is not required, because plugin can generate simple bean class (select "NONE" for annotation type). If you have more information in this question - please write.

**Comment by ccqy66** [comment]
about this question,you can see it.  https://github.com/alibaba/fastjson/wiki/JSONField

**Comment by robohorse** [comment]
ok, i see. Thanks). Yes you are welcome if you want! Support for this feature will be great.

Also annotations is required because plugin format fields for java compatibility. I mean something like this
 "1_field" - > `@SerializedName("1_filed")
  @Expose
  private int jsonMember1Filed;`

**Comment by robohorse** [comment]
also you have broken git settings: your email is [not recognized](https://github.com/robohorse/RoboPOJOGenerator/commit/f7bdd4cf826bf95e4597af95faf7ddcc6b195081) )

**Comment by ccqy66** [comment]
hmm,I don't notice,I will fix it.my email is chenchen_839@126.com

**Comment by ccqy66** [comment]
ok,I will do it soon.

**Comment by robohorse** [comment]
i resolved this issue because i need it now, sorry)
